=== atile-y/SyntaxHighlighter/web/WEB-INF/data/schema/keywordsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2014 Alejandro Alberto Yescas Benitez.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://www.w3.org/keywords"
           targetNamespace="http://www.w3.org/keywords"
           elementFormDefault="qualified"
           xmlns:codes="http://www.w3.org/codes">

<xs:complexType name="langType">
    <xs:sequence>
        <xs:element name="keyword" maxOccurs="unbounded" type="xs:string"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="langsType">
    <xs:choice>
        <xs:element name="Bash" type="langType"/>
        <xs:element name="CSharp" type="langType"/>
        <xs:element name="C" type="langType"/>
        <xs:element name="Cpp" type="langType"/>
        <xs:element name="CSS" type="langType"/>
        <xs:element name="JavaScript" type="langType"/>
        <xs:element name="Java" type="langType"/>
        <xs:element name="PHP" type="langType"/>
        <xs:element name="Python" type="langType"/>
        <xs:element name="SQL" type="langType"/>
        <xs:element name="VisualBasic" type="langType"/>
        <xs:element name="XML" type="langType"/>
        <xs:element name="XHTML" type="langType"/>
        <xs:element name="HTML" type="langType"/>
    </xs:choice>
</xs:complexType>

<xs:element name="lenguajes" type="langsType"/>

</xs:schema>

=== atile-y/SyntaxHighlighter/web/WEB-INF/data/CSSKeywords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2014 Alejandro Alberto Yescas Benitez.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<nsKeywords:lenguajes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:nsKeywords='http://www.w3.org/keywords'
    xsi:schemaLocation='http://www.w3.org/keywords schema/keywordsSchema.xsd'>
    <nsKeywords:CSS>
        <nsKeywords:keyword>ascent</nsKeywords:keyword>
        <nsKeywords:keyword>azimuth</nsKeywords:keyword>
        <nsKeywords:keyword>background</nsKeywords:keyword>
        <nsKeywords:keyword>background-attachment</nsKeywords:keyword>
        <nsKeywords:keyword>background-color</nsKeywords:keyword>
        <nsKeywords:keyword>background-image</nsKeywords:keyword>
        <nsKeywords:keyword>background-position</nsKeywords:keyword>
        <nsKeywords:keyword>background-repeat</nsKeywords:keyword>
        <nsKeywords:keyword>baseline</nsKeywords:keyword>
        <nsKeywords:keyword>bbox</nsKeywords:keyword>
        <nsKeywords:keyword>border</nsKeywords:keyword>
        <nsKeywords:keyword>border-bottom</nsKeywords:keyword>
        <nsKeywords:keyword>border-bottom-color</nsKeywords:keyword>
        <nsKeywords:keyword>border-bottom-style</nsKeywords:keyword>
        <nsKeywords:keyword>border-bottom-width</nsKeywords:keyword>
        <nsKeywords:keyword>border-collapse</nsKeywords:keyword>
        <nsKeywords:keyword>border-color</nsKeywords:keyword>
        <nsKeywords:keyword>border-left</nsKeywords:keyword>
        <nsKeywords:keyword>border-left-color</nsKeywords:keyword>
        <nsKeywords:keyword>border-left-style</nsKeywords:keyword>
        <nsKeywords:keyword>border-left-width</nsKeywords:keyword>
        <nsKeywords:keyword>border-right</nsKeywords:keyword>
        <nsKeywords:keyword>border-right-color</nsKeywords:keyword>
        <nsKeywords:keyword>border-right-style</nsKeywords:keyword>
        <nsKeywords:keyword>border-right-width</nsKeywords:keyword>
        <nsKeywords:keyword>border-spacing</nsKeywords:keyword>
        <nsKeywords:keyword>border-style</nsKeywords:keyword>
        <nsKeywords:keyword>border-top</nsKeywords:keyword>
        <nsKeywords:keyword>border-top-color</nsKeywords:keyword>
        <nsKeywords:keyword>border-top-style</nsKeywords:keyword>
        <nsKeywords:keyword>border-top-width</nsKeywords:keyword>
        <nsKeywords:keyword>border-width</nsKeywords:keyword>
        <nsKeywords:keyword>bottom</nsKeywords:keyword>
        <nsKeywords:keyword>cap-height</nsKeywords:keyword>
        <nsKeywords:keyword>caption-side</nsKeywords:keyword>
        <nsKeywords:keyword>centerline</nsKeywords:keyword>
        <nsKeywords:keyword>clear</nsKeywords:keyword>
        <nsKeywords:keyword>clip</nsKeywords:keyword>
        <nsKeywords:keyword>color</nsKeywords:keyword>
        <nsKeywords:keyword>content</nsKeywords:keyword>
        <nsKeywords:keyword>counter-increment</nsKeywords:keyword>
        <nsKeywords:keyword>counter-reset</nsKeywords:keyword>
        <nsKeywords:keyword>cue</nsKeywords:keyword>
        <nsKeywords:keyword>cue-after</nsKeywords:keyword>
        <nsKeywords:keyword>cue-before</nsKeywords:keyword>
        <nsKeywords:keyword>cursor</nsKeywords:keyword>
        <nsKeywords:keyword>definition-src</nsKeywords:keyword>
        <nsKeywords:keyword>descent</nsKeywords:keyword>
        <nsKeywords:keyword>direction</nsKeywords:keyword>
        <nsKeywords:keyword>display</nsKeywords:keyword>
        <nsKeywords:keyword>elevation</nsKeywords:keyword>
        <nsKeywords:keyword>empty-cells</nsKeywords:keyword>
        <nsKeywords:keyword>float</nsKeywords:keyword>
        <nsKeywords:keyword>font</nsKeywords:keyword>
        <nsKeywords:keyword>font-family</nsKeywords:keyword>
        <nsKeywords:keyword>font-size</nsKeywords:keyword>
        <nsKeywords:keyword>font-size-adjust</nsKeywords:keyword>
        <nsKeywords:keyword>font-stretch</nsKeywords:keyword>
        <nsKeywords:keyword>font-style</nsKeywords:keyword>
        <nsKeywords:keyword>font-variant</nsKeywords:keyword>
        <nsKeywords:keyword>font-weight</nsKeywords:keyword>
        <nsKeywords:keyword>height</nsKeywords:keyword>
        <nsKeywords:keyword>left</nsKeywords:keyword>
        <nsKeywords:keyword>letter-spacing</nsKeywords:keyword>
        <nsKeywords:keyword>line-height</nsKeywords:keyword>
        <nsKeywords:keyword>list-style</nsKeywords:keyword>
        <nsKeywords:keyword>list-style-image</nsKeywords:keyword>
        <nsKeywords:keyword>list-style-position</nsKeywords:keyword>
        <nsKeywords:keyword>list-style-type</nsKeywords:keyword>
        <nsKeywords:keyword>margin</nsKeywords:keyword>
        <nsKeywords:keyword>margin-bottom</nsKeywords:keyword>
        <nsKeywords:keyword>margin-left</nsKeywords:keyword>
        <nsKeywords:keyword>margin-right</nsKeywords:keyword>
        <nsKeywords:keyword>margin-top</nsKeywords:keyword>
        <nsKeywords:keyword>marker-offset</nsKeywords:keyword>
        <nsKeywords:keyword>marks</nsKeywords:keyword>
        <nsKeywords:keyword>mathline</nsKeywords:keyword>
        <nsKeywords:keyword>max-height</nsKeywords:keyword>
        <nsKeywords:keyword>max-width</nsKeywords:keyword>
        <nsKeywords:keyword>min-height</nsKeywords:keyword>
        <nsKeywords:keyword>min-width</nsKeywords:keyword>
        <nsKeywords:keyword>orphans</nsKeywords:keyword>
        <nsKeywords:keyword>outline</nsKeywords:keyword>
        <nsKeywords:keyword>outline-color</nsKeywords:keyword>
        <nsKeywords:keyword>outline-style</nsKeywords:keyword>
        <nsKeywords:keyword>outline-width</nsKeywords:keyword>
        <nsKeywords:keyword>overflow</nsKeywords:keyword>
        <nsKeywords:keyword>padding</nsKeywords:keyword>
        <nsKeywords:keyword>padding-bottom</nsKeywords:keyword>
        <nsKeywords:keyword>padding-left</nsKeywords:keyword>
        <nsKeywords:keyword>padding-right</nsKeywords:keyword>
        <nsKeywords:keyword>padding-top</nsKeywords:keyword>
        <nsKeywords:keyword>page</nsKeywords:keyword>
        <nsKeywords:keyword>page-break-after</nsKeywords:keyword>
        <nsKeywords:keyword>page-break-before</nsKeywords:keyword>
        <nsKeywords:keyword>page-break-inside</nsKeywords:keyword>
        <nsKeywords:keyword>pause</nsKeywords:keyword>
        <nsKeywords:keyword>pause-after</nsKeywords:keyword>
        <nsKeywords:keyword>pause-before</nsKeywords:keyword>
        <nsKeywords:keyword>pitch</nsKeywords:keyword>
        <nsKeywords:keyword>pitch-range</nsKeywords:keyword>
        <nsKeywords:keyword>play-during</nsKeywords:keyword>
        <nsKeywords:keyword>position</nsKeywords:keyword>
        <nsKeywords:keyword>quotes</nsKeywords:keyword>
        <nsKeywords:keyword>richness</nsKeywords:keyword>
        <nsKeywords:keyword>right</nsKeywords:keyword>
        <nsKeywords:keyword>size</nsKeywords:keyword>
        <nsKeywords:keyword>slope</nsKeywords:keyword>
        <nsKeywords:keyword>speak</nsKeywords:keyword>
        <nsKeywords:keyword>speak-header</nsKeywords:keyword>
        <nsKeywords:keyword>speak-numeral</nsKeywords:keyword>
        <nsKeywords:keyword>speak-punctuation</nsKeywords:keyword>
        <nsKeywords:keyword>speech-rate</nsKeywords:keyword>
        <nsKeywords:keyword>src</nsKeywords:keyword>
        <nsKeywords:keyword>stemh</nsKeywords:keyword>
        <nsKeywords:keyword>stemv</nsKeywords:keyword>
        <nsKeywords:keyword>stress</nsKeywords:keyword>
        <nsKeywords:keyword>table-layout</nsKeywords:keyword>
        <nsKeywords:keyword>text-align</nsKeywords:keyword>
        <nsKeywords:keyword>text-decoration</nsKeywords:keyword>
        <nsKeywords:keyword>text-indent</nsKeywords:keyword>
        <nsKeywords:keyword>text-shadow</nsKeywords:keyword>
        <nsKeywords:keyword>text-transform</nsKeywords:keyword>
        <nsKeywords:keyword>top</nsKeywords:keyword>
        <nsKeywords:keyword>unicode-bidi</nsKeywords:keyword>
        <nsKeywords:keyword>unicode-range</nsKeywords:keyword>
        <nsKeywords:keyword>units-per-em</nsKeywords:keyword>
        <nsKeywords:keyword>vertical-align</nsKeywords:keyword>
        <nsKeywords:keyword>visibility</nsKeywords:keyword>
        <nsKeywords:keyword>voice-family</nsKeywords:keyword>
        <nsKeywords:keyword>volume</nsKeywords:keyword>
        <nsKeywords:keyword>white-space</nsKeywords:keyword>
        <nsKeywords:keyword>widows</nsKeywords:keyword>
        <nsKeywords:keyword>width</nsKeywords:keyword>
        <nsKeywords:keyword>widths</nsKeywords:keyword>
        <nsKeywords:keyword>word-spacing</nsKeywords:keyword>
        <nsKeywords:keyword>x-height</nsKeywords:keyword>
        <nsKeywords:keyword>z-index</nsKeywords:keyword>
    </nsKeywords:CSS>
</nsKeywords:lenguajes>

=== atile-y/SyntaxHighlighter/build/web/WEB-INF/data/PythonKeywords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2014 Alejandro Alberto Yescas Benitez.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<nsKeywords:lenguajes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:nsKeywords='http://www.w3.org/keywords'
    xsi:schemaLocation='http://www.w3.org/keywords schema/keywordsSchema.xsd'>
    <nsKeywords:Python>
        <nsKeywords:keyword>and</nsKeywords:keyword>
        <nsKeywords:keyword>assert</nsKeywords:keyword>
        <nsKeywords:keyword>break</nsKeywords:keyword>
        <nsKeywords:keyword>class</nsKeywords:keyword>
        <nsKeywords:keyword>continue</nsKeywords:keyword>
        <nsKeywords:keyword>def</nsKeywords:keyword>
        <nsKeywords:keyword>del</nsKeywords:keyword>
        <nsKeywords:keyword>elif</nsKeywords:keyword>
        <nsKeywords:keyword>else</nsKeywords:keyword>
        <nsKeywords:keyword>except</nsKeywords:keyword>
        <nsKeywords:keyword>exec</nsKeywords:keyword>
        <nsKeywords:keyword>finally</nsKeywords:keyword>
        <nsKeywords:keyword>for</nsKeywords:keyword>
        <nsKeywords:keyword>from</nsKeywords:keyword>
        <nsKeywords:keyword>global</nsKeywords:keyword>
        <nsKeywords:keyword>if</nsKeywords:keyword>
        <nsKeywords:keyword>import</nsKeywords:keyword>
        <nsKeywords:keyword>in</nsKeywords:keyword>
        <nsKeywords:keyword>is</nsKeywords:keyword>
        <nsKeywords:keyword>lambda</nsKeywords:keyword>
        <nsKeywords:keyword>not</nsKeywords:keyword>
        <nsKeywords:keyword>or</nsKeywords:keyword>
        <nsKeywords:keyword>pass</nsKeywords:keyword>
        <nsKeywords:keyword>print</nsKeywords:keyword>
        <nsKeywords:keyword>raise</nsKeywords:keyword>
        <nsKeywords:keyword>return</nsKeywords:keyword>
        <nsKeywords:keyword>try</nsKeywords:keyword>
        <nsKeywords:keyword>while</nsKeywords:keyword>
        <nsKeywords:keyword>yield</nsKeywords:keyword>
    </nsKeywords:Python>
</nsKeywords:lenguajes>

=== atile-y/SyntaxHighlighter/web/WEB-INF/data/CppKeywords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2014 Alejandro Alberto Yescas Benitez.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<nsKeywords:lenguajes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:nsKeywords='http://www.w3.org/keywords'
    xsi:schemaLocation='http://www.w3.org/keywords schema/keywordsSchema.xsd'>
    <nsKeywords:Cpp>
        <nsKeywords:keyword>and</nsKeywords:keyword>
        <nsKeywords:keyword>and_eq</nsKeywords:keyword>
        <nsKeywords:keyword>asm</nsKeywords:keyword>
        <nsKeywords:keyword>auto</nsKeywords:keyword>
        <nsKeywords:keyword>bitand</nsKeywords:keyword>
        <nsKeywords:keyword>bitor</nsKeywords:keyword>
        <nsKeywords:keyword>bool</nsKeywords:keyword>
        <nsKeywords:keyword>break</nsKeywords:keyword>
        <nsKeywords:keyword>case</nsKeywords:keyword>
        <nsKeywords:keyword>catch</nsKeywords:keyword>
        <nsKeywords:keyword>char</nsKeywords:keyword>
        <nsKeywords:keyword>class</nsKeywords:keyword>
        <nsKeywords:keyword>compl</nsKeywords:keyword>
        <nsKeywords:keyword>const</nsKeywords:keyword>
        <nsKeywords:keyword>const_cast</nsKeywords:keyword>
        <nsKeywords:keyword>continue</nsKeywords:keyword>
        <nsKeywords:keyword>default</nsKeywords:keyword>
        <nsKeywords:keyword>delete</nsKeywords:keyword>
        <nsKeywords:keyword>do</nsKeywords:keyword>
        <nsKeywords:keyword>double</nsKeywords:keyword>
        <nsKeywords:keyword>dynamic_cast</nsKeywords:keyword>
        <nsKeywords:keyword>else</nsKeywords:keyword>
        <nsKeywords:keyword>enum</nsKeywords:keyword>
        <nsKeywords:keyword>explicit</nsKeywords:keyword>
        <nsKeywords:keyword>export</nsKeywords:keyword>
        <nsKeywords:keyword>extern</nsKeywords:keyword>
        <nsKeywords:keyword>false</nsKeywords:keyword>
        <nsKeywords:keyword>float</nsKeywords:keyword>
        <nsKeywords:keyword>for</nsKeywords:keyword>
        <nsKeywords:keyword>friend</nsKeywords:keyword>
        <nsKeywords:keyword>goto</nsKeywords:keyword>
        <nsKeywords:keyword>if</nsKeywords:keyword>
        <nsKeywords:keyword>inline</nsKeywords:keyword>
        <nsKeywords:keyword>int</nsKeywords:keyword>
        <nsKeywords:keyword>long</nsKeywords:keyword>
        <nsKeywords:keyword>mutable</nsKeywords:keyword>
        <nsKeywords:keyword>namespace</nsKeywords:keyword>
        <nsKeywords:keyword>new</nsKeywords:keyword>
        <nsKeywords:keyword>not</nsKeywords:keyword>
        <nsKeywords:keyword>not_eq</nsKeywords:keyword>
        <nsKeywords:keyword>operator</nsKeywords:keyword>
        <nsKeywords:keyword>or</nsKeywords:keyword>
        <nsKeywords:keyword>or_eq</nsKeywords:keyword>
        <nsKeywords:keyword>private</nsKeywords:keyword>
        <nsKeywords:keyword>protected</nsKeywords:keyword>
        <nsKeywords:keyword>public</nsKeywords:keyword>
        <nsKeywords:keyword>register</nsKeywords:keyword>
        <nsKeywords:keyword>reinterpret_cast</nsKeywords:keyword>
        <nsKeywords:keyword>return</nsKeywords:keyword>
        <nsKeywords:keyword>short</nsKeywords:keyword>
        <nsKeywords:keyword>signed</nsKeywords:keyword>
        <nsKeywords:keyword>sizeof</nsKeywords:keyword>
        <nsKeywords:keyword>static</nsKeywords:keyword>
        <nsKeywords:keyword>static_cast</nsKeywords:keyword>
        <nsKeywords:keyword>struct</nsKeywords:keyword>
        <nsKeywords:keyword>switch</nsKeywords:keyword>
        <nsKeywords:keyword>template</nsKeywords:keyword>
        <nsKeywords:keyword>this</nsKeywords:keyword>
        <nsKeywords:keyword>throw</nsKeywords:keyword>
        <nsKeywords:keyword>true</nsKeywords:keyword>
        <nsKeywords:keyword>try</nsKeywords:keyword>
        <nsKeywords:keyword>typedef</nsKeywords:keyword>
        <nsKeywords:keyword>typeid</nsKeywords:keyword>
        <nsKeywords:keyword>typename</nsKeywords:keyword>
        <nsKeywords:keyword>union</nsKeywords:keyword>
        <nsKeywords:keyword>unsigned</nsKeywords:keyword>
        <nsKeywords:keyword>using</nsKeywords:keyword>
        <nsKeywords:keyword>virtual</nsKeywords:keyword>
        <nsKeywords:keyword>void</nsKeywords:keyword>
        <nsKeywords:keyword>volatile</nsKeywords:keyword>
        <nsKeywords:keyword>wchar_t</nsKeywords:keyword>
        <nsKeywords:keyword>while</nsKeywords:keyword>
        <nsKeywords:keyword>xor</nsKeywords:keyword>
        <nsKeywords:keyword>xor_eq</nsKeywords:keyword>
    </nsKeywords:Cpp>
</nsKeywords:lenguajes>

=== atile-y/SyntaxHighlighter/build/web/WEB-INF/data/PHPKeywords.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
The MIT License

Copyright 2014 Alejandro Alberto Yescas Benitez.

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
-->


<nsKeywords:lenguajes
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns:nsKeywords='http://www.w3.org/keywords'
    xsi:schemaLocation='http://www.w3.org/keywords schema/keywordsSchema.xsd'>
    <nsKeywords:PHP>
        <nsKeywords:keyword>abstract</nsKeywords:keyword>
        <nsKeywords:keyword>and</nsKeywords:keyword>
        <nsKeywords:keyword>array</nsKeywords:keyword>
        <nsKeywords:keyword>as</nsKeywords:keyword>
        <nsKeywords:keyword>break</nsKeywords:keyword>
        <nsKeywords:keyword>case</nsKeywords:keyword>
        <nsKeywords:keyword>catch</nsKeywords:keyword>
        <nsKeywords:keyword>cfunction</nsKeywords:keyword>
        <nsKeywords:keyword>class</nsKeywords:keyword>
        <nsKeywords:keyword>clone</nsKeywords:keyword>
        <nsKeywords:keyword>const</nsKeywords:keyword>
        <nsKeywords:keyword>continue</nsKeywords:keyword>
        <nsKeywords:keyword>declare</nsKeywords:keyword>
        <nsKeywords:keyword>default</nsKeywords:keyword>
        <nsKeywords:keyword>die</nsKeywords:keyword>
        <nsKeywords:keyword>do</nsKeywords:keyword>
        <nsKeywords:keyword>else</nsKeywords:keyword>
        <nsKeywords:keyword>elseif</nsKeywords:keyword>
        <nsKeywords:keyword>enddeclare</nsKeywords:keyword>
        <nsKeywords:keyword>endfor</nsKeywords:keyword>
        <nsKeywords:keyword>endforeach</nsKeywords:keyword>
        <nsKeywords:keyword>endif</nsKeywords:keyword>
        <nsKeywords:keyword>endswitch</nsKeywords:keyword>
        <nsKeywords:keyword>endwhile</nsKeywords:keyword>
        <nsKeywords:keyword>extends</nsKeywords:keyword>
        <nsKeywords:keyword>final</nsKeywords:keyword>
        <nsKeywords:keyword>for</nsKeywords:keyword>
        <nsKeywords:keyword>foreach</nsKeywords:keyword>
        <nsKeywords:keyword>function</nsKeywords:keyword>
        <nsKeywords:keyword>global</nsKeywords:keyword>
        <nsKeywords:keyword>goto</nsKeywords:keyword>
        <nsKeywords:keyword>if</nsKeywords:keyword>
        <nsKeywords:keyword>implements</nsKeywords:keyword>
        <nsKeywords:keyword>include</nsKeywords:keyword>
        <nsKeywords:keyword>include_once</nsKeywords:keyword>
        <nsKeywords:keyword>instanceof</nsKeywords:keyword>
        <nsKeywords:keyword>interface</nsKeywords:keyword>
        <nsKeywords:keyword>namespace</nsKeywords:keyword>
        <nsKeywords:keyword>new</nsKeywords:keyword>
        <nsKeywords:keyword>old_function</nsKeywords:keyword>
        <nsKeywords:keyword>or</nsKeywords:keyword>
        <nsKeywords:keyword>private</nsKeywords:keyword>
        <nsKeywords:keyword>protected</nsKeywords:keyword>
        <nsKeywords:keyword>public</nsKeywords:keyword>
        <nsKeywords:keyword>require</nsKeywords:keyword>
        <nsKeywords:keyword>require_once</nsKeywords:keyword>
        <nsKeywords:keyword>return</nsKeywords:keyword>
        <nsKeywords:keyword>static</nsKeywords:keyword>
        <nsKeywords:keyword>switch</nsKeywords:keyword>
        <nsKeywords:keyword>throw</nsKeywords:keyword>
        <nsKeywords:keyword>try</nsKeywords:keyword>
        <nsKeywords:keyword>use</nsKeywords:keyword>
        <nsKeywords:keyword>var</nsKeywords:keyword>
        <nsKeywords:keyword>while</nsKeywords:keyword>
        <nsKeywords:keyword>xor</nsKeywords:keyword>
    </nsKeywords:PHP>
</nsKeywords:lenguajes>
